version: '3'

services:
  
  backend:
    container_name: express
    build: ./backend
    ports:
      - ${PORT_BACKEND}:3000
  
  frontend:
    container_name: angular
    build: ./frontend
    ports:
      - ${PORT_FRONTEND}:80
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - ${PORT_MONGO}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - ${PORT_MONGOEXPRESS}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT}:${MONGO_PASS}@mongodb:27017/

networks:
  defualt:
    name: app
